package org.getopt.pcl5.PCL5Interpreter;

import java.util.HashMap;

public class TypefaceInfo {
  private final static int FONTNAME_MASK = 0xFFF;

  private static HashMap _fontnameMap;
  private static HashMap _vendorMap;

  public static String getFontName(int fontID) {
    if (_fontnameMap == null)
      init();

    return (String) _fontnameMap.get(new Integer(fontID & FONTNAME_MASK));
  }

  public static String getVendorName(int fontID) {
    if (_vendorMap == null)
      init();

    return (String) _vendorMap.get(new Integer(fontID & ~FONTNAME_MASK));
  }

  private static void init() {
    _fontnameMap = new HashMap();
    _vendorMap = new HashMap();

    _vendorMap.put(new Integer(0x1000), "AGFA");
    _vendorMap.put(new Integer(0x2000), "Bitstream Inc.");
    _vendorMap.put(new Integer(0x3000), "Linotype Company");
    _vendorMap.put(new Integer(0x4000), "Monotype Corporation");
    _vendorMap.put(new Integer(0x5000), "Adobe Systems");
    _vendorMap.put(new Integer(0x7000), "Bigelow & Holmes");

    _fontnameMap.put(new Integer(0), "Line Printer");
    _fontnameMap.put(new Integer(2), "Elite");
    _fontnameMap.put(new Integer(3), "Courier");
    _fontnameMap.put(new Integer(4), "Helvetica");
    _fontnameMap.put(new Integer(5), "Times Roman");
    _fontnameMap.put(new Integer(6), "Letter Gothic");
    _fontnameMap.put(new Integer(7), "Script");
    _fontnameMap.put(new Integer(8), "Prestige");
    _fontnameMap.put(new Integer(9), "Caslon 540 & No. 3");
    // _fontnameMap.put(new Integer(9), "Caslon Antique (contour)");
    // _fontnameMap.put(new Integer(9), "Caslon Open Face (inline)");
    _fontnameMap.put(new Integer(10), "Orator");
    _fontnameMap.put(new Integer(11), "Presentation");
    _fontnameMap.put(new Integer(13), "Serifa");
    _fontnameMap.put(new Integer(14), "Futura");
    _fontnameMap.put(new Integer(14), "Greek Futura");
    _fontnameMap.put(new Integer(15), "Palatino");
    _fontnameMap.put(new Integer(16), "ITC Souvenir");
    // _fontnameMap.put(new Integer(16), "ITC Souvenir Greek");
    _fontnameMap.put(new Integer(17), "Optima");
    // _fontnameMap.put(new Integer(17), "Safeer (Arabic)");
    // _fontnameMap.put(new Integer(17), "Komain (Thai)");
    // _fontnameMap.put(new Integer(17), "Greek Oracle");
    _fontnameMap.put(new Integer(18), "ITC Garamond");
    _fontnameMap.put(new Integer(20), "Coronet (italic)");
    // _fontnameMap.put(new Integer(20), "Chevalier (bold expanded pattern 0)");
    _fontnameMap.put(new Integer(21), "Broadway");
    _fontnameMap.put(new Integer(23), "Century Schoolbook");
    // _fontnameMap.put(new Integer(23), "Greek & Math Serif");
    _fontnameMap.put(new Integer(24), "University Roman");
    _fontnameMap.put(new Integer(27), "ITC Korinna");
    _fontnameMap.put(new Integer(28), "Naskh");
    _fontnameMap.put(new Integer(29), "Cloister Black");
    _fontnameMap.put(new Integer(30), "ITC Galliard");
    _fontnameMap.put(new Integer(31), "ITC Avant Garde Gothic");
    // _fontnameMap.put(new Integer(31), "Tom (Thai))");
    _fontnameMap.put(new Integer(32), "Brush (italic)");
    // _fontnameMap.put(new Integer(32), "Stop");
    _fontnameMap.put(new Integer(33), "Blippo (black)");
    // _fontnameMap.put(new Integer(33), "Tea Chest (condensed)");
    _fontnameMap.put(new Integer(34), "Hobo");
    _fontnameMap.put(new Integer(35), "Windsor");
    _fontnameMap.put(new Integer(38), "Peignot");
    _fontnameMap.put(new Integer(39), "Baskerville");
    _fontnameMap.put(new Integer(41), "Trade Gothic");
    // _fontnameMap.put(new Integer(41), "Pemai (Thai)");
    // _fontnameMap.put(new Integer(41), "CG Trade");
    _fontnameMap.put(new Integer(42), "Goudy Old Style");
    _fontnameMap.put(new Integer(43), "ITC Zapf Chancery");
    _fontnameMap.put(new Integer(44), "Clarendon");
    _fontnameMap.put(new Integer(45), "ITC Zapf Dingbats");
    _fontnameMap.put(new Integer(46), "Cooper");
    _fontnameMap.put(new Integer(47), "ITC Bookman");
    // _fontnameMap.put(new Integer(47), "Noparat (Thai)");
    _fontnameMap.put(new Integer(48), "Stick");
    _fontnameMap.put(new Integer(49), "HP-GL Drafting");
    _fontnameMap.put(new Integer(50), "HP-GL Spline");
    _fontnameMap.put(new Integer(51), "Gill Sans");
    // _fontnameMap.put(new Integer(51), "Unesco (Thai)");
    _fontnameMap.put(new Integer(52), "Univers");
    _fontnameMap.put(new Integer(53), "Bodoni");
    // _fontnameMap.put(new Integer(53), "Poster Bodoni (black)");
    // _fontnameMap.put(new Integer(53), "Greek Apla");
    _fontnameMap.put(new Integer(54), "Rockwell");
    _fontnameMap.put(new Integer(55), "Melior");
    _fontnameMap.put(new Integer(56), "ITC Tiffany");
    _fontnameMap.put(new Integer(57), "ITC Clearface");
    _fontnameMap.put(new Integer(58), "Amelia");
    _fontnameMap.put(new Integer(59), "Park Avenue (italic)");
    _fontnameMap.put(new Integer(59), "Falstaff (black)");
    _fontnameMap.put(new Integer(60), "Handel Gothic");
    _fontnameMap.put(new Integer(61), "Dom Casual");
    _fontnameMap.put(new Integer(62), "ITC Benguiat");
    _fontnameMap.put(new Integer(63), "ITC Cheltenham");
    _fontnameMap.put(new Integer(64), "Century Expanded");
    _fontnameMap.put(new Integer(65), "Franklin Gothic");
    // _fontnameMap.put(new Integer(65), "Paetai (Thai)");
    _fontnameMap.put(new Integer(68), "Plantin");
    _fontnameMap.put(new Integer(69), "Trump Mediaeval");
    _fontnameMap.put(new Integer(70), "Futura Black");
    _fontnameMap.put(new Integer(71), "ITC American Typewriter");
    _fontnameMap.put(new Integer(72), "Antique Olive");
    // _fontnameMap.put(new Integer(72), "Greek Antique Olive");
    _fontnameMap.put(new Integer(73), "Uncial");
    _fontnameMap.put(new Integer(74), "ITC Bauhaus");
    _fontnameMap.put(new Integer(75), "Century Old Style");
    _fontnameMap.put(new Integer(76), "ITC Eras");
    _fontnameMap.put(new Integer(77), "Friz Quadrata (ITC)");
    _fontnameMap.put(new Integer(78), "ITC Lubalin Graph");
    _fontnameMap.put(new Integer(79), "Eurostile");
    // _fontnameMap.put(new Integer(79), "Intanon (Thai)");
    _fontnameMap.put(new Integer(79), "Greek Microstyle");
    _fontnameMap.put(new Integer(80), "Mincho (Japanese)");
    // _fontnameMap.put(new Integer(80), "Myoungjo (Korean)");
    // _fontnameMap.put(new Integer(80),
    // "HanYang Batang Proportional (Korean)");
    _fontnameMap.put(new Integer(81), "ITC Serif Gothic");
    // _fontnameMap.put(new Integer(81), "Saemmul (Korea)");
    // _fontnameMap.put(new Integer(81), "Sammul (Korea)");
    _fontnameMap.put(new Integer(82), "Snell Roundhand");
    // _fontnameMap.put(new Integer(82), "Pilgy (Korean)");
    _fontnameMap.put(new Integer(83), "Souvenir Gothic");
    _fontnameMap.put(new Integer(84), "Stymie");
    _fontnameMap.put(new Integer(87), "Bernhard Modern");
    _fontnameMap.put(new Integer(89), "Excelsior");
    _fontnameMap.put(new Integer(90), "Gando Ronde Script");
    _fontnameMap.put(new Integer(91), "Ondine");
    // _fontnameMap.put(new Integer(91), "EACT (Thai)");
    _fontnameMap.put(new Integer(92), "P. T. Barnum");
    _fontnameMap.put(new Integer(93), "Kaufmann");
    // _fontnameMap.put(new Integer(93), "U-Thong (Thai)");
    _fontnameMap.put(new Integer(94), "ITC Bolt (extended)");
    // _fontnameMap.put(new Integer(94), "ITC Machine (condensed)");
    _fontnameMap.put(new Integer(97), "Revue");
    _fontnameMap.put(new Integer(101), "Garamond (Stempel)");
    _fontnameMap.put(new Integer(102), "Garth Graphic");
    _fontnameMap.put(new Integer(103), "ITC Ronda");
    // _fontnameMap.put(new Integer(103), "Candy Bits (patterned)");
    _fontnameMap.put(new Integer(104), "OCR-A");
    _fontnameMap.put(new Integer(105), "Cochin");
    _fontnameMap.put(new Integer(106), "Englische Schreibschrift (italic)");
    // _fontnameMap.put(new Integer(106), "Mister Earl (condensed)");
    _fontnameMap.put(new Integer(107), "Flash (italic)");
    // _fontnameMap.put(new Integer(107), "Woodstock");
    _fontnameMap.put(new Integer(108), "Gothic (numbered)");
    _fontnameMap.put(new Integer(109), "Stencil (ATF)");
    _fontnameMap.put(new Integer(110), "OCR-B");
    _fontnameMap.put(new Integer(111), "Akzidenz-Grotesk");
    _fontnameMap.put(new Integer(112),
            "Black White (patterned, outline, inline)");
    // _fontnameMap.put(new Integer(112), "Logos");
    _fontnameMap.put(new Integer(113), "Shannon");
    _fontnameMap.put(new Integer(114), "ITC Stone Informal");
    _fontnameMap.put(new Integer(115), "ITC Stone Sans");
    _fontnameMap.put(new Integer(116), "ITC Stone Serif");
    _fontnameMap.put(new Integer(117), "Schneidler Mediaeval");
    _fontnameMap.put(new Integer(118), "ITC Symbol");
    _fontnameMap.put(new Integer(119), "ITC Weidemann");
    _fontnameMap.put(new Integer(120), "Copperplate Gothic (display)");
    _fontnameMap.put(new Integer(121), "Trajan");
    _fontnameMap.put(new Integer(122), "Concorde");
    _fontnameMap.put(new Integer(123), "Janson Text");
    _fontnameMap.put(new Integer(124), "Linotype Centennial");
    _fontnameMap.put(new Integer(125), "Life");
    _fontnameMap.put(new Integer(126), "Minister");
    _fontnameMap.put(new Integer(127), "New Century Schoolbook");
    _fontnameMap.put(new Integer(152), "Maru Gosikku (round gothic Japan)");
    // _fontnameMap.put(new Integer(152), "Gulrim (Korean)");
    // _fontnameMap.put(new Integer(152),
    // "HanYang Gulrim Proportional (Korean)");
    _fontnameMap.put(new Integer(153), "Gosikku (Kaku, gothic Japan)");
    // _fontnameMap.put(new Integer(153), "Gothic (Japan, Fixed Pitch)");
    // _fontnameMap.put(new Integer(153),
    // "HanYang Dotum Proportional (Korean)");
    _fontnameMap.put(new Integer(154), "Socho");
    _fontnameMap.put(new Integer(155), "Kyokasho (text book)");
    _fontnameMap.put(new Integer(156), "Kaisho");
    _fontnameMap.put(new Integer(157), "Traditional Arabic Script");
    _fontnameMap.put(new Integer(158), "Arabic News");
    _fontnameMap.put(new Integer(159), "Post Antiqua");
    _fontnameMap.put(new Integer(160), "Aerospace Pi");
    // _fontnameMap.put(new Integer(160), "Devanagari (Hindi)");
    _fontnameMap.put(new Integer(161), "Maritime Pi");
    // _fontnameMap.put(new Integer(161), "Krishna (Gujarati)");
    _fontnameMap.put(new Integer(162), "Bits Pic Pi");
    // _fontnameMap.put(new Integer(162), "Ranjit (Gurmukhi)");
    _fontnameMap.put(new Integer(163), "Keycap Pi");
    // _fontnameMap.put(new Integer(163), "Raj Raja (Tamil)");
    _fontnameMap.put(new Integer(164), "Tieman");
    // _fontnameMap.put(new Integer(164), "Gyosho");
    _fontnameMap.put(new Integer(165), "David");
    _fontnameMap.put(new Integer(166), "Nork");
    _fontnameMap.put(new Integer(167), "Ousbouh");
    _fontnameMap.put(new Integer(168), "Koufi");
    _fontnameMap.put(new Integer(169), "Italia (ITC)");
    _fontnameMap.put(new Integer(169), "Hadassah");
    _fontnameMap.put(new Integer(170), "Bembo");
    // _fontnameMap.put(new Integer(170), "Sharif");
    _fontnameMap.put(new Integer(171), "Aachen");
    // _fontnameMap.put(new Integer(171), "Malik");
    _fontnameMap.put(new Integer(172), "Americana");
    _fontnameMap.put(new Integer(173), "Arnold Boecklin");
    _fontnameMap.put(new Integer(174), "Copperplate Gothic (text)");
    _fontnameMap.put(new Integer(175), "Belwe");
    _fontnameMap.put(new Integer(176), "ITC Berkeley Oldstyle");
    _fontnameMap.put(new Integer(177), "Frutiger");
    _fontnameMap.put(new Integer(178), "Candida");
    _fontnameMap.put(new Integer(179), "Folio");
    _fontnameMap.put(new Integer(180), "Corona");
    _fontnameMap.put(new Integer(181), "ITC Kabel");
    // _fontnameMap.put(new Integer(181), "Zeppelin (inline)");
    _fontnameMap.put(new Integer(182), "Garamond No. 3");
    _fontnameMap.put(new Integer(183), "Sabon");
    _fontnameMap.put(new Integer(184), "ITC Novarese");
    _fontnameMap.put(new Integer(185), "Weiss");
    _fontnameMap.put(new Integer(186), "Hiroshige");
    _fontnameMap.put(new Integer(187), "French Script");
    _fontnameMap.put(new Integer(188), "Meridien");
    _fontnameMap.put(new Integer(189), "Mistral");
    _fontnameMap.put(new Integer(190), "Aster");
    _fontnameMap.put(new Integer(191), "Caledonia");
    _fontnameMap.put(new Integer(192), "Nuptial Script");
    _fontnameMap.put(new Integer(193), "Lucida");
    _fontnameMap.put(new Integer(194), "Song (China)");
    _fontnameMap.put(new Integer(194), "Adobe Wood Series 1");
    _fontnameMap.put(new Integer(195), "Memphis");
    _fontnameMap.put(new Integer(196), "Lucida Sans");
    _fontnameMap.put(new Integer(197), "Syntax");
    _fontnameMap.put(new Integer(198), "Utopia");
    _fontnameMap.put(new Integer(199), "Berthold Walbaum Buch");
    _fontnameMap.put(new Integer(200), "Minion");
    _fontnameMap.put(new Integer(201), "Marigold");
    _fontnameMap.put(new Integer(202), "ITC Tiepolo");
    _fontnameMap.put(new Integer(203), "Versailles");
    _fontnameMap.put(new Integer(204), "ITC Leawood");
    _fontnameMap.put(new Integer(205), "ITC Caslon No. 224");
    _fontnameMap.put(new Integer(206), "ITC Cushing");
    _fontnameMap.put(new Integer(207), "ITC Fenice");
    _fontnameMap.put(new Integer(208), "ITC Usherwood");
    _fontnameMap.put(new Integer(209), "ITC Benguiat Gothic");
    _fontnameMap.put(new Integer(210), "Spartan");
    // _fontnameMap.put(new Integer(210), "ITC Ozwald (fatface)");
    _fontnameMap.put(new Integer(211), "Neuzeit Grotesk");
    _fontnameMap.put(new Integer(212), "PMN Caecilia");
    _fontnameMap.put(new Integer(213), "ITC Busorama");
    _fontnameMap.put(new Integer(214), "Agfa Wile Roman");
    _fontnameMap.put(new Integer(215), "ITC Zapf International");
    _fontnameMap.put(new Integer(216), "Poppl-Pontifex");
    _fontnameMap.put(new Integer(217), "ITC Quay Sans");
    _fontnameMap.put(new Integer(218), "Arial");
    _fontnameMap.put(new Integer(219), "Fairfield");
    _fontnameMap.put(new Integer(220), "ITC Zapf Book");
    _fontnameMap.put(new Integer(221), "Lucida Casual");
    // _fontnameMap.put(new Integer(221), "Linotype Technical Pi 1 & 2");
    _fontnameMap.put(new Integer(222), "Graphite");
    // _fontnameMap.put(new Integer(222), "Linotype Textil Pi 1 & 2");
    _fontnameMap.put(new Integer(223), "Poetica");
    // _fontnameMap.put(new Integer(223), "Century Schoolbook Monospace");
    _fontnameMap.put(new Integer(224), "Berliner Grotesk");
    _fontnameMap.put(new Integer(225), "Christiana");
    _fontnameMap.put(new Integer(226), "Comenius-Antiqua");
    _fontnameMap.put(new Integer(227), "Delta");
    _fontnameMap.put(new Integer(228), "Italian Old Style");
    _fontnameMap.put(new Integer(229), "Zingo");
    _fontnameMap.put(new Integer(230), "Octavian");
    // _fontnameMap.put(new Integer(230), "Borders & Ornaments 1");
    _fontnameMap.put(new Integer(231), "Footlight");
    // _fontnameMap.put(new Integer(231), "Borders & Ornaments 4");
    _fontnameMap.put(new Integer(232), "Apollo");
    // _fontnameMap.put(new Integer(232), "Borders & Ornaments 5");
    _fontnameMap.put(new Integer(233), "Bremen");
    // _fontnameMap.put(new Integer(233), "Borders & Ornaments 6");
    _fontnameMap.put(new Integer(234), "Oranda");
    // _fontnameMap.put(new Integer(234), "Communication 1");
    _fontnameMap.put(new Integer(235), "Nubian");
    // _fontnameMap.put(new Integer(235), "Communication 2");
    _fontnameMap.put(new Integer(236), "Cataneo");
    // _fontnameMap.put(new Integer(236), "Communication 3");
    _fontnameMap.put(new Integer(237), "Wittenberger Fraktur");
    // _fontnameMap.put(new Integer(237), "Communication 6");
    _fontnameMap.put(new Integer(238), "Modern");
    // _fontnameMap.put(new Integer(238), "PL Modern");
    // _fontnameMap.put(new Integer(238), "Games & Sports 1");
    _fontnameMap.put(new Integer(239), "Artistik");
    // _fontnameMap.put(new Integer(239), "Games & Sports 2");
    _fontnameMap.put(new Integer(240), "Flintstones");
    // _fontnameMap.put(new Integer(240), "Games & Sports 3");
    _fontnameMap.put(new Integer(241), "SnowCap");
    // _fontnameMap.put(new Integer(241), "Games & Sports 4");
    _fontnameMap.put(new Integer(242), "Bedrock");
    // _fontnameMap.put(new Integer(242), "Holidays 1");
    _fontnameMap.put(new Integer(243), "Star Fleet");
    // _fontnameMap.put(new Integer(243), "Industry & Engineering 1");
    _fontnameMap.put(new Integer(244), "Star Trek Film");
    // _fontnameMap.put(new Integer(244), "Industry & Engineering 2");
    _fontnameMap.put(new Integer(245), "Star Trek");
    // _fontnameMap.put(new Integer(245), "Transportation 1");
    _fontnameMap.put(new Integer(246), "Hei (China)");
    // _fontnameMap.put(new Integer(246), "Star Trek Pi");
    _fontnameMap.put(new Integer(246), "Transportation 2");
    _fontnameMap.put(new Integer(247), "ITC Mendoza");
    _fontnameMap.put(new Integer(248), "Boton");
    _fontnameMap.put(new Integer(249), "Jaeger Daily News");
    _fontnameMap.put(new Integer(250), "ITC Officina Serif");
    _fontnameMap.put(new Integer(251), "ITC Officina Sans");
    _fontnameMap.put(new Integer(252), "Goudy Modern");
    _fontnameMap.put(new Integer(253), "Scotch Roman");
    _fontnameMap.put(new Integer(254), "Temporary-Only Font");
    _fontnameMap.put(new Integer(256), "Bar Codes");
    _fontnameMap.put(new Integer(257), "Hadriano");
    _fontnameMap.put(new Integer(258), "Joanna");
    _fontnameMap.put(new Integer(259), "Onyx");
    _fontnameMap.put(new Integer(260), "Cyrillic Helvetica");
    // _fontnameMap.put(new Integer(260), "Greek Helvetica");
    // _fontnameMap.put(new Integer(260), "East Asian Helvetica");
    _fontnameMap.put(new Integer(261), "Cyrillic Times");
    // _fontnameMap.put(new Integer(261), "Greek Times");
    // _fontnameMap.put(new Integer(261), "East Asian Times");
    _fontnameMap.put(new Integer(262), "ITC Quorum");
    _fontnameMap.put(new Integer(263), "Engravers� Old English");
    _fontnameMap.put(new Integer(264), "Kennerley");
    _fontnameMap.put(new Integer(265), "Adobe Caslon");
    _fontnameMap.put(new Integer(266), "Albertus");
    _fontnameMap.put(new Integer(267), "New Aurora Grotesque");
    _fontnameMap.put(new Integer(268), "TBG Omnia");
    _fontnameMap.put(new Integer(269), "Glypha");
    _fontnameMap.put(new Integer(270), "Tempo");
    // _fontnameMap.put(new Integer(270), "Umbra (open shadow)");
    _fontnameMap.put(new Integer(271), "American Text");
    _fontnameMap.put(new Integer(272), "Pasquale");
    _fontnameMap.put(new Integer(273), "ITC Elan");
    _fontnameMap.put(new Integer(274), "Monotype Goudy Sans");
    _fontnameMap.put(new Integer(275), "Lutheresche Fraktur");
    // _fontnameMap.put(new Integer(275), "Universal News & Commercial Pi");
    _fontnameMap.put(new Integer(276), "Thunderbird (extra condensed)");
    // _fontnameMap.put(new Integer(276), "ITC Honda (black)");
    _fontnameMap.put(new Integer(277), "Shelley");
    // _fontnameMap.put(new Integer(277), "Mr. Big");
    _fontnameMap.put(new Integer(278), "Macbeth");
    // _fontnameMap.put(new Integer(278), "Universal Greek & Math Pi");
    _fontnameMap.put(new Integer(279), "ITC Century");
    _fontnameMap.put(new Integer(280), "Vineta");
    _fontnameMap.put(new Integer(281), "TBG Duc de Berry");
    _fontnameMap.put(new Integer(282), "Times Europa");
    _fontnameMap.put(new Integer(283), "ITC Jamille");
    _fontnameMap.put(new Integer(284), "Flyer");
    _fontnameMap.put(new Integer(285), "Wedding Text");
    _fontnameMap.put(new Integer(286), "Carolina");
    _fontnameMap.put(new Integer(287), "Avenir");
    _fontnameMap.put(new Integer(288), "Lucia");
    _fontnameMap.put(new Integer(289), "Tekton");
    _fontnameMap.put(new Integer(290), "Charme");
    _fontnameMap.put(new Integer(291), "ITC Flora");
    _fontnameMap.put(new Integer(292), "Basilica");
    _fontnameMap.put(new Integer(293), "Auriol");
    _fontnameMap.put(new Integer(294), "Kuenstler Script");
    _fontnameMap.put(new Integer(295), "ITC New Baskerville");
    _fontnameMap.put(new Integer(296), "Berling");
    _fontnameMap.put(new Integer(297), "News Gothic");
    _fontnameMap.put(new Integer(298), "Critter");
    // _fontnameMap.put(new Integer(298), "Linotype Holiday Pi 1, 2, & 3");
    _fontnameMap.put(new Integer(299), "Medici Script");
    _fontnameMap.put(new Integer(300), "Aurora");
    _fontnameMap.put(new Integer(301), "Carta");
    _fontnameMap.put(new Integer(302), "Adobe Symbol");
    _fontnameMap.put(new Integer(303), "Insignia");
    _fontnameMap.put(new Integer(304), "Perpetua");
    _fontnameMap.put(new Integer(305), "Raleigh");
    _fontnameMap.put(new Integer(306), "Romic");
    _fontnameMap.put(new Integer(307), "Formata");
    _fontnameMap.put(new Integer(308), "Cyrillic Univers");
    _fontnameMap.put(new Integer(308), "Chuan Pim (like Univers)");
    _fontnameMap.put(new Integer(308), "Narkis Tam (like Univers)");
    _fontnameMap.put(new Integer(308), "Greek Univers II");
    _fontnameMap.put(new Integer(309), "Bauer Bodoni");
    _fontnameMap.put(new Integer(310), "Industria");
    _fontnameMap.put(new Integer(311), "Cutout");
    // _fontnameMap.put(new Integer(311), "Decoration Pi");
    _fontnameMap.put(new Integer(312), "Letraset Bramley");
    _fontnameMap.put(new Integer(313), "Isabella");
    _fontnameMap.put(new Integer(314), "Cascade Script");
    _fontnameMap.put(new Integer(315), "VAG Rounded");
    _fontnameMap.put(new Integer(316), "Russell Square");
    _fontnameMap.put(new Integer(317), "Liberty");
    _fontnameMap.put(new Integer(318), "ITC Esprit");
    _fontnameMap.put(new Integer(319), "Clairvaux");
    _fontnameMap.put(new Integer(320), "Raphael");
    _fontnameMap.put(new Integer(321), "ITC Franklin Gothic");
    _fontnameMap.put(new Integer(322), "Murray Hill");
    _fontnameMap.put(new Integer(323), "Baker Signet");
    _fontnameMap.put(new Integer(324), "Mythos");
    _fontnameMap.put(new Integer(324), "Gambling Pi");
    _fontnameMap.put(new Integer(325), "San Marco");
    _fontnameMap.put(new Integer(326), "Typo Roman");
    _fontnameMap.put(new Integer(327), "Engravers Text (inline)");
    _fontnameMap.put(new Integer(327), "New Berolina (italic)");
    _fontnameMap.put(new Integer(328), "Orbit-B");
    _fontnameMap.put(new Integer(329), "McCollough");
    _fontnameMap.put(new Integer(330), "ITC Isadora");
    _fontnameMap.put(new Integer(331), "Giddyup");
    _fontnameMap.put(new Integer(331), "Audio Pi");
    _fontnameMap.put(new Integer(332), "Letraset Crillee");
    _fontnameMap.put(new Integer(333), "Agfa Nadianne");
    _fontnameMap.put(new Integer(334), "Compliment");
    _fontnameMap.put(new Integer(335), "ITC Giovanni");
    _fontnameMap.put(new Integer(336), "Neuzeit S");
    _fontnameMap.put(new Integer(337), "Erbar");
    _fontnameMap.put(new Integer(338), "Parisian");
    _fontnameMap.put(new Integer(339), "Nofret");
    _fontnameMap.put(new Integer(340), "City");
    _fontnameMap.put(new Integer(341), "Old Style 7");
    _fontnameMap.put(new Integer(342), "Bell Centennial");
    _fontnameMap.put(new Integer(343), "Lydian");
    _fontnameMap.put(new Integer(344), "Monotype Ellington");
    _fontnameMap.put(new Integer(345), "Impressum");
    _fontnameMap.put(new Integer(346), "Reporter No. 2");
    _fontnameMap.put(new Integer(347), "Freestyle Script");
    _fontnameMap.put(new Integer(348), "Serpentine");
    _fontnameMap.put(new Integer(349), "Lithos");
    _fontnameMap.put(new Integer(350), "Basilia");
    _fontnameMap.put(new Integer(351), "Simplified Arabic");
    _fontnameMap.put(new Integer(352), "Maximus");
    _fontnameMap.put(new Integer(353), "ITC Slimbach");
    _fontnameMap.put(new Integer(357), "Berthold Garamond");
    _fontnameMap.put(new Integer(358), "Rad");
    _fontnameMap.put(new Integer(358), "Land Pi");
    _fontnameMap.put(new Integer(359), "Oxford (italic)");
    _fontnameMap.put(new Integer(359), "Kino (bold condensed)");
    _fontnameMap.put(new Integer(360), "Looney Tunes");
    _fontnameMap.put(new Integer(360), "E13B MICR");
    _fontnameMap.put(new Integer(361), "Imperial");
    _fontnameMap.put(new Integer(361), "CMC-7 MICR");
    _fontnameMap.put(new Integer(362), "Charlemagne");
    _fontnameMap.put(new Integer(363), "Present Script");
    _fontnameMap.put(new Integer(364), "Repro Script (italic)");
    _fontnameMap.put(new Integer(364), "Matura (bold)");
    _fontnameMap.put(new Integer(365), "Baskerville No. 2");
    _fontnameMap.put(new Integer(366), "Engravers� Roman");
    _fontnameMap.put(new Integer(367), "VGC Egyptian 505");
    _fontnameMap.put(new Integer(368), "TBG Herculanum");
    _fontnameMap.put(new Integer(369), "Clearface Gothic");
    _fontnameMap.put(new Integer(370), "Studz");
    // _fontnameMap.put(new Integer(370), "Border Pi 1515-9");
    _fontnameMap.put(new Integer(371), "Toolbox");
    // _fontnameMap.put(new Integer(371), "Bundesbahn Pi");
    _fontnameMap.put(new Integer(372), "Quake");
    // _fontnameMap.put(new Integer(372), "Chemical Pi");
    _fontnameMap.put(new Integer(373), "Neuland (solid & inline)");
    // _fontnameMap.put(new Integer(373), "Newton Inline");
    // _fontnameMap.put(new Integer(373), "Warning Pi");
    _fontnameMap.put(new Integer(374), "Harry");
    _fontnameMap.put(new Integer(375), "Alternate Gothic (numbered)");
    _fontnameMap.put(new Integer(376), "Figaro");
    _fontnameMap.put(new Integer(377), "Formal Script");
    _fontnameMap.put(new Integer(378), "Holland Title");
    _fontnameMap.put(new Integer(379), "ITC Barcelona");
    _fontnameMap.put(new Integer(380), "Cartier");
    _fontnameMap.put(new Integer(381), "Deepdene");
    _fontnameMap.put(new Integer(382), "Delphin");
    _fontnameMap.put(new Integer(383), "Parsons");
    _fontnameMap.put(new Integer(384), "Brighton");
    _fontnameMap.put(new Integer(385), "Berthold Barmeno");
    _fontnameMap.put(new Integer(386), "Berthold Colossalis");
    _fontnameMap.put(new Integer(387), "Berthold Cosmos");
    _fontnameMap.put(new Integer(388), "ITC Isbell");
    _fontnameMap.put(new Integer(389), "ITC Mixage");
    _fontnameMap.put(new Integer(390), "Sonata");
    _fontnameMap.put(new Integer(390), "Badr, or Bayaan II");
    _fontnameMap.put(new Integer(391), "ITC Newtext");
    _fontnameMap.put(new Integer(392), "Happening");
    _fontnameMap.put(new Integer(393), "Menue");
    _fontnameMap.put(new Integer(394), "Doric");
    _fontnameMap.put(new Integer(395), "S�maragd");
    _fontnameMap.put(new Integer(396), "Pierrot");
    // _fontnameMap.put(new Integer(396), "Ornaments");
    _fontnameMap.put(new Integer(397), "Berthold Bodoni Old Face");
    _fontnameMap.put(new Integer(398), "Schadow");
    _fontnameMap.put(new Integer(399), "Akzidens Grotesk Buch");
    _fontnameMap.put(new Integer(400), "Akzidens Grotesk Buch Stencil");
    _fontnameMap.put(new Integer(401), "Akzidens Grotesk Buch Schulbuch");
    _fontnameMap.put(new Integer(402), "Bookman");
    _fontnameMap.put(new Integer(403), "Bruce Old Style");
    _fontnameMap.put(new Integer(404), "Bulmer");
    _fontnameMap.put(new Integer(405), "Madison");
    _fontnameMap.put(new Integer(406), "Textype");
    _fontnameMap.put(new Integer(407), "Primer");
    _fontnameMap.put(new Integer(408), "Garamond (Simoncini)");
    _fontnameMap.put(new Integer(409), "Adobe Wood Series 2");
    _fontnameMap.put(new Integer(410), "Rotis Serif");
    // _fontnameMap.put(new Integer(410), "Caravan LH One");
    _fontnameMap.put(new Integer(411), "Rotis Semiserif");
    // _fontnameMap.put(new Integer(411), "Caravan LH Two");
    _fontnameMap.put(new Integer(412), "Rotis Sans Serif");
    // _fontnameMap.put(new Integer(412), "Caravan LH Three");
    _fontnameMap.put(new Integer(413), "Rotis Semisans");
    // _fontnameMap.put(new Integer(413), "Caravan LH Four");
    _fontnameMap.put(new Integer(414), "Arcadia");
    _fontnameMap.put(new Integer(415), "ITC Veljovik");
    _fontnameMap.put(new Integer(416), "Armenian Aramian");
    _fontnameMap.put(new Integer(417), "Armenian Barz");
    _fontnameMap.put(new Integer(418), "Helvetica Rounded");
    _fontnameMap.put(new Integer(419), "Olympian");
    _fontnameMap.put(new Integer(420), "DIN Engschrift (condensed)");
    // _fontnameMap.put(new Integer(420), "DIN Mittelschrift");
    _fontnameMap.put(new Integer(421), "Granjon");
    _fontnameMap.put(new Integer(422), "Guardi");
    _fontnameMap.put(new Integer(423), "Impact");
    _fontnameMap.put(new Integer(424), "Sassoon Primary");
    _fontnameMap.put(new Integer(425), "Packard");
    _fontnameMap.put(new Integer(426), "Baskerville Book");
    _fontnameMap.put(new Integer(427), "ITC Pacella");
    _fontnameMap.put(new Integer(428), "Rusticana");
    _fontnameMap.put(new Integer(429), "Eccentric");
    _fontnameMap.put(new Integer(430), "Embassy Script");
    // _fontnameMap.put(new Integer(430), "Greek Florentine Script II");
    _fontnameMap.put(new Integer(431), "PL Latin Bold");
    // _fontnameMap.put(new Integer(431), "PL Latin Elongated (condensed)");
    // _fontnameMap.put(new Integer(431), "Latin Antique");
    // _fontnameMap.put(new Integer(431), "Latin Wide (extended)");
    _fontnameMap.put(new Integer(432), "ITC Modern 216");
    _fontnameMap.put(new Integer(433), "Serlio");
    _fontnameMap.put(new Integer(434), "Piranesi");
    _fontnameMap.put(new Integer(435), "Imago");
    _fontnameMap.put(new Integer(436), "Wilke");
    _fontnameMap.put(new Integer(437), "Cyrillic 22");
    _fontnameMap.put(new Integer(438), "Adobe Garamond");
    _fontnameMap.put(new Integer(439), "Seagull");
    _fontnameMap.put(new Integer(440), "Latin MT");
    _fontnameMap.put(new Integer(441), "Runic MT");
    _fontnameMap.put(new Integer(442), "Moore Computer");
    _fontnameMap.put(new Integer(443), "Commercial Script");
    _fontnameMap.put(new Integer(444), "Dominante");
    _fontnameMap.put(new Integer(445), "Wilhelm Klingspor Gotisch");
    _fontnameMap.put(new Integer(446), "Trajanus");
    _fontnameMap.put(new Integer(447), "TSI Caxton");
    // _fontnameMap.put(new Integer(447), "Letraset Caxton");
    _fontnameMap.put(new Integer(448), "Fette Fraktur");
    // _fontnameMap.put(new Integer(448), "Sapphire (pattern 0)");
    // _fontnameMap.put(new Integer(448), "Saphir (pattern 0)");
    _fontnameMap.put(new Integer(449), "Rainbow Bass (pattern 0)");
    _fontnameMap.put(new Integer(449), "European Pi");
    _fontnameMap.put(new Integer(450), "Banco");
    _fontnameMap.put(new Integer(451), "Bodoni Antiqua");
    _fontnameMap.put(new Integer(452), "Sallwey Script");
    // _fontnameMap.put(new Integer(452), "Mathematical Pi");
    _fontnameMap.put(new Integer(453), "Congress");
    _fontnameMap.put(new Integer(454), "Cheq");
    _fontnameMap.put(new Integer(455), "Berthold Walbaum Buch (B.metrics)");
    _fontnameMap.put(new Integer(456), "Huxley Vertical");
    _fontnameMap.put(new Integer(457), "Grayda");
    _fontnameMap.put(new Integer(458), "Penfield No. 3");
    _fontnameMap.put(new Integer(459), "Michelangelo");
    _fontnameMap.put(new Integer(460), "Neo Didot");
    _fontnameMap.put(new Integer(461), "Berthold Caslon Buch");
    _fontnameMap.put(new Integer(462), "Sans No. 1");
    _fontnameMap.put(new Integer(463), "Torino");
    _fontnameMap.put(new Integer(464), "Photina");
    _fontnameMap.put(new Integer(465), "Calligraphiques");
    _fontnameMap.put(new Integer(466), "Concorde Nova");
    _fontnameMap.put(new Integer(467), "Franco");
    _fontnameMap.put(new Integer(468), "Goudy Text");
    _fontnameMap.put(new Integer(469), "Balloon (italic)");
    _fontnameMap.put(new Integer(470), "Eusebius");
    _fontnameMap.put(new Integer(470), "Eusebius Open (inline)");
    _fontnameMap.put(new Integer(471), "Digital");
    // _fontnameMap.put(new Integer(471), "Noris Script (italic)");
    _fontnameMap.put(new Integer(472), "Poppl-Pontifex (B.metrics)");
    _fontnameMap.put(new Integer(473), "Amigo");
    // _fontnameMap.put(new Integer(473), "Pelican (italic)");
    _fontnameMap.put(new Integer(473), "Visigoth (bold italic)");
    _fontnameMap.put(new Integer(474), "Letraset Arta");
    _fontnameMap.put(new Integer(475), "Post Mediaval");
    _fontnameMap.put(new Integer(476), "Adsans");
    _fontnameMap.put(new Integer(477), "Ariadne");
    _fontnameMap.put(new Integer(478), "Calligraphy");
    _fontnameMap.put(new Integer(479), "Didot");
    _fontnameMap.put(new Integer(480), "Ashley Script (italic)");
    // _fontnameMap.put(new Integer(480), "Ashley Crawford (bold)");
    // _fontnameMap.put(new Integer(480), "Ashley Inline (inline)");
    _fontnameMap.put(new Integer(481), "Catull");
    _fontnameMap.put(new Integer(482), "Cremona");
    _fontnameMap.put(new Integer(483), "Audrey No. 2");
    _fontnameMap.put(new Integer(484), "Lo-Type");
    _fontnameMap.put(new Integer(485), "Madame (patterned with shadow)");
    _fontnameMap.put(new Integer(486), "Roundy");
    // _fontnameMap.put(new Integer(486), "Animals");
    _fontnameMap.put(new Integer(487), "Ruling Script");
    // _fontnameMap.put(new Integer(487), "Business & Services 1");
    _fontnameMap.put(new Integer(488), "Sho");
    // _fontnameMap.put(new Integer(488), "Business & Services 2");
    _fontnameMap.put(new Integer(489), "Wiesbaden Swing");
    // _fontnameMap.put(new Integer(489), "Commercial 1");
    _fontnameMap.put(new Integer(490), "Star Trek Next");
    // _fontnameMap.put(new Integer(490), "Commercial 2");
    _fontnameMap.put(new Integer(491), "ITC Highlander");
    // _fontnameMap.put(new Integer(491), "Ecology");
    _fontnameMap.put(new Integer(492), "Helios II");
    // _fontnameMap.put(new Integer(492), "General Symbols 1");
    _fontnameMap.put(new Integer(493), "Kai Medium");
    // _fontnameMap.put(new Integer(493), "General Symbols 2");
    _fontnameMap.put(new Integer(494), "Medical & Pharmaceutical 1");
    _fontnameMap.put(new Integer(495), "Space");
    // _fontnameMap.put(new Integer(495), "Musical");
    _fontnameMap.put(new Integer(496), "Special Alphabets 4");
    _fontnameMap.put(new Integer(497), "Special Alphabets 5");
    _fontnameMap.put(new Integer(498), "Special Alphabets 6");
    _fontnameMap.put(new Integer(499), "Inflex");
    _fontnameMap.put(new Integer(500), "Monotype Old Style");
    _fontnameMap.put(new Integer(501), "Ming");
    _fontnameMap.put(new Integer(502), "FangSong");
    _fontnameMap.put(new Integer(503), "Helinda Rook");
    _fontnameMap.put(new Integer(504), "Original Script");
    _fontnameMap.put(new Integer(505), "Citadel Script");
    _fontnameMap.put(new Integer(506), "Old Fashion Script");
    _fontnameMap.put(new Integer(507), "ITC Legacy Serif");
    _fontnameMap.put(new Integer(508), "ITC Legacy Sans");
    _fontnameMap.put(new Integer(509), "Athenaeum");
    // _fontnameMap.put(new Integer(509), "Athenaeum Negative (pattern 0)");
    // _fontnameMap.put(new Integer(509), "Athenaeum Positive (pattern 1)");
    _fontnameMap.put(new Integer(510), "ITC Anna (condensed)");
    // _fontnameMap.put(new Integer(510), "ITC Beesknees (black)");
    _fontnameMap.put(new Integer(511), "ITC Studio Script (italic)");
    // _fontnameMap.put(new Integer(511), "ITC Mona Lisa Recut (inline)");
    // _fontnameMap.put(new Integer(511), "ITC Mona Lisa Solid (upright)");
    _fontnameMap.put(new Integer(512), "Sackers Square Gothic");
    // _fontnameMap.put(new Integer(512), "Sackers English Script");
    _fontnameMap.put(new Integer(513), "Heritage");
    _fontnameMap.put(new Integer(514), "Sackers Gothic");
    _fontnameMap.put(new Integer(516), "Greek Helios II");
    _fontnameMap.put(new Integer(517), "Times New Roman"); // was
                                                           // "Times (Ten, New, etc.)");
    _fontnameMap.put(new Integer(518), "Berthold Script");
    _fontnameMap.put(new Integer(519), "Bernhard Tango (italic)");
    _fontnameMap.put(new Integer(520), "Castellar (inline)");
    _fontnameMap.put(new Integer(521), "Else");
    _fontnameMap.put(new Integer(522), "Basque (condensed)");
    // _fontnameMap.put(new Integer(522), "Palace Script (italic)");
    _fontnameMap.put(new Integer(523), "Centaur");
    _fontnameMap.put(new Integer(524), "Fine Hand");
    _fontnameMap.put(new Integer(525), "Linotype Astrology Pi");
    _fontnameMap.put(new Integer(526), "Sackers Roman");
    _fontnameMap.put(new Integer(527), "Kompakt (ultra black italic)");
    // _fontnameMap.put(new Integer(527), "Monoline Script (italic)");
    _fontnameMap.put(new Integer(528), "Othello (bold condensed)");
    _fontnameMap.put(new Integer(529), "Sackers Classic Roman");
    // _fontnameMap.put(new Integer(529), "Sackers Italian Script (italic)");
    _fontnameMap.put(new Integer(530), "Musketeer");
    // _fontnameMap.put(new Integer(530), "Riviera (inline)");
    _fontnameMap.put(new Integer(531), "Poppl-Residenz");
    _fontnameMap.put(new Integer(532), "Rotation");
    _fontnameMap.put(new Integer(533), "Bank Gothic");
    _fontnameMap.put(new Integer(534), "Delphian (inline)");
    // _fontnameMap.put(new Integer(534), "Greeting Monotone");
    _fontnameMap.put(new Integer(535), "Sackers Antique Roman");
    _fontnameMap.put(new Integer(536), "Schwabacher");
    _fontnameMap.put(new Integer(537), "Egyptienne (condensed)");
    _fontnameMap.put(new Integer(538), "Artisan Roman (inline)");
    // _fontnameMap.put(new Integer(538), "Forte (bold italic)");
    _fontnameMap.put(new Integer(539), "Burin Roman");
    // _fontnameMap.put(new Integer(539), "Burin Sans (light)");
    _fontnameMap.put(new Integer(540), "Hellenic Wide (extended)");
    _fontnameMap.put(new Integer(541), "Thompson Quillscript");
    _fontnameMap.put(new Integer(542), "Kartoon");
    _fontnameMap.put(new Integer(543), "Classic Roman");
    _fontnameMap.put(new Integer(544), "AG Old Face");
    _fontnameMap.put(new Integer(545), "Lucian");
    _fontnameMap.put(new Integer(546), "Della Robbia");
    _fontnameMap.put(new Integer(547), "Libra");
    _fontnameMap.put(new Integer(548), "Brody (bold upright)");
    _fontnameMap.put(new Integer(549), "Ad Lib (bold)");
    _fontnameMap.put(new Integer(550), "Choc (black)");
    _fontnameMap.put(new Integer(551), "Handle Oldstyle");
    _fontnameMap.put(new Integer(552), "Roman");
    _fontnameMap.put(new Integer(553), "Antique Roman");
    _fontnameMap.put(new Integer(554),
            "Goudy Catalogue, addt�l Old Style faces");
    // _fontnameMap.put(new Integer(554), "Goudy Handtooled (inline)");
    // _fontnameMap.put(new Integer(554), "Goudy Heavyface (black)");
    _fontnameMap.put(new Integer(555), "Calligrapher");
    _fontnameMap.put(new Integer(556), "Lucida Bright");
    _fontnameMap.put(new Integer(557), "Pi Collection");
    _fontnameMap.put(new Integer(558), "Broadpen");
    _fontnameMap.put(new Integer(559), "Amazone");
    _fontnameMap.put(new Integer(560), "Frank Ruehl");
    _fontnameMap.put(new Integer(561), "Cloe");
    _fontnameMap.put(new Integer(562), "Discus");
    _fontnameMap.put(new Integer(563), "Myriad");
    _fontnameMap.put(new Integer(565), "WTC Our Bodoni");
    _fontnameMap.put(new Integer(566), "Ideal Schreibschrift");
    _fontnameMap.put(new Integer(567), "Print");
    _fontnameMap.put(new Integer(568), "Lucida Blackletter");
    _fontnameMap.put(new Integer(569), "Lucida Calligraphy");
    _fontnameMap.put(new Integer(570), "Data 70");
    _fontnameMap.put(new Integer(571), "Compacta (expanded)");
    // _fontnameMap.put(new Integer(571), "Helvetica Inserat (condensed)");
    _fontnameMap.put(new Integer(572), "Lucida Handwriting");
    // _fontnameMap.put(new Integer(572), "Milestones");
    _fontnameMap.put(new Integer(573), "Biffo");
    _fontnameMap.put(new Integer(574), "Calvert");
    _fontnameMap.put(new Integer(575), "Cantoria");
    _fontnameMap.put(new Integer(576), "Dorchester Script");
    _fontnameMap.put(new Integer(577), "Grotesque");
    _fontnameMap.put(new Integer(578), "Pepita");
    _fontnameMap.put(new Integer(579), "Vectora");
    _fontnameMap.put(new Integer(580), "Script Bold");
    _fontnameMap.put(new Integer(581), "Spectrum");
    _fontnameMap.put(new Integer(582), "Boulevard");
    _fontnameMap.put(new Integer(583), "Cheltenham");
    _fontnameMap.put(new Integer(584), "De Vinne");
    _fontnameMap.put(new Integer(585), "London Text (inline)");
    _fontnameMap.put(new Integer(585), "Profil (bold italic inline)");
    _fontnameMap.put(new Integer(586), "Imprint");
    _fontnameMap.put(new Integer(587), "Allegro (bold italic)");
    // _fontnameMap.put(new Integer(587), "Engraver�s Gothic (text)");
    _fontnameMap.put(new Integer(588), "Bernhard (bold condensed)");
    // _fontnameMap.put(new Integer(588), "Eckmann (text)");
    _fontnameMap.put(new Integer(589), "Cloister Open Face (outline)");
    // _fontnameMap.put(new Integer(589), "Davida (text)");
    // _fontnameMap.put(new Integer(589), "Klang (italic)");
    _fontnameMap.put(new Integer(590), "Fry�s Baskerville");
    _fontnameMap.put(new Integer(591), "Metro");
    _fontnameMap.put(new Integer(592), "Mandate");
    _fontnameMap.put(new Integer(593), "Star Trek Gen");
    _fontnameMap.put(new Integer(594), "Virile");
    _fontnameMap.put(new Integer(595), "Bingham Script (text)");
    _fontnameMap.put(new Integer(595), "Block (bold)");
    _fontnameMap.put(new Integer(596), "ITC Gorilla (text)");
    _fontnameMap.put(new Integer(596), "ITC Pioneer (outline shadow)");
    _fontnameMap.put(new Integer(597), "Ruzicka");
    _fontnameMap.put(new Integer(598), "Bodoni Campanile");
    _fontnameMap.put(new Integer(599), "Linotype Modern");
    _fontnameMap.put(new Integer(600), "Monterey Script (italic)");
    // _fontnameMap.put(new Integer(600), "Playbill (condensed)");
    _fontnameMap.put(new Integer(601), "Normande");
    _fontnameMap.put(new Integer(602), "Wave");
    _fontnameMap.put(new Integer(603), "Bernhard Fashion (extra light)");
    // _fontnameMap.put(new Integer(603), "Mercurius");
    _fontnameMap.put(new Integer(604), "Stuyvesant (inline)");
    _fontnameMap.put(new Integer(605), "Impuls (italic)");
    // _fontnameMap.put(new Integer(605), "Romana (text & bold)");
    _fontnameMap.put(new Integer(606), "Shotgun");
    _fontnameMap.put(new Integer(607), "Ehrhardt");
    _fontnameMap.put(new Integer(608), "ITC Grizzly");
    _fontnameMap.put(new Integer(609), "ITC Grouch");
    _fontnameMap.put(new Integer(610), "ITC Tom�s New Roman");
    _fontnameMap.put(new Integer(611), "Palette (italic)");
    _fontnameMap.put(new Integer(611), "Hanseatic (ultrabold condensed)");
    _fontnameMap.put(new Integer(612), "Bison");
    _fontnameMap.put(new Integer(613), "Jefferson");
    _fontnameMap.put(new Integer(614), "Electra");
    _fontnameMap.put(new Integer(615), "Antique No. 3");
    _fontnameMap.put(new Integer(616), "Flemish Script (italic)");
    _fontnameMap.put(new Integer(617), "Hallmark Bodoni");
    _fontnameMap.put(new Integer(618), "Modern #20");
    _fontnameMap.put(new Integer(619), "Westinghouse Gothic");
    _fontnameMap.put(new Integer(620), "Bloc (outline)");
    // _fontnameMap.put(new Integer(620), "Empire (ultra condensed)");
    _fontnameMap.put(new Integer(621), "Oscar");
    _fontnameMap.put(new Integer(622), "Eagle Bold");
    _fontnameMap.put(new Integer(622), "Joanna Solotype (inline)");
    _fontnameMap.put(new Integer(623), "Akzidenz-Grotesk (B.metrics)");
    _fontnameMap.put(new Integer(624), "Koch Antiqua");
    _fontnameMap.put(new Integer(625), "Mirarae");
    _fontnameMap.put(new Integer(626), "Horley Old Style");
    _fontnameMap.put(new Integer(627), "Tango");
    _fontnameMap.put(new Integer(628), "Pifont Circle Numbers");
    _fontnameMap.put(new Integer(629), "Pifont OCRA Numbers");
    _fontnameMap.put(new Integer(630), "Pifont Square Numbers");
    _fontnameMap.put(new Integer(631), "Pifont Triangle Numbers");
    _fontnameMap.put(new Integer(632), "Bank Script (italic)");
    _fontnameMap.put(new Integer(633), "Serlio Dekoration (pi numbers)");
    _fontnameMap.put(new Integer(634), "Concorde (B.metrics)");
    _fontnameMap.put(new Integer(635), "Jets");
    _fontnameMap.put(new Integer(636), "Jetsons");
    _fontnameMap.put(new Integer(637), "Looney Type");
    _fontnameMap.put(new Integer(638), "Pompeijana");
    _fontnameMap.put(new Integer(639), "Rusticana (Frutiger)");
    _fontnameMap.put(new Integer(640), "Notre Dame");
    _fontnameMap.put(new Integer(641), "Beverly Hills (inline)");
    _fontnameMap.put(new Integer(641), "Lotus (pattern 0)");
    _fontnameMap.put(new Integer(642), "Advertisers Gothic Light");
    _fontnameMap.put(new Integer(642), "Eclipse (pattern 0)");
    _fontnameMap.put(new Integer(643), "Capone Light");
    _fontnameMap.put(new Integer(643), "Victorian Silhouette (contour)");
    _fontnameMap.put(new Integer(644), "Dynamo (extra bold)");
    _fontnameMap.put(new Integer(644), "Modernistic (inline)");
    _fontnameMap.put(new Integer(645), "Gallia (inline)");
    _fontnameMap.put(new Integer(645), "Skjald");
    _fontnameMap.put(new Integer(646), "Bell Gothic");
    _fontnameMap.put(new Integer(647), "Gillies Gothic Bold (italic)");
    _fontnameMap.put(new Integer(648), "Quaint Roman");
    _fontnameMap.put(new Integer(648), "Chic (inline)");
    _fontnameMap.put(new Integer(649), "PL Westerveldt Light (condensed)");
    _fontnameMap.put(new Integer(650), "PL Davison Americana");
    _fontnameMap.put(new Integer(651), "TC Jasper");
    _fontnameMap.put(new Integer(652), "Poppl-Laudatio");
    _fontnameMap.put(new Integer(653), "TC Europa Bold");
    _fontnameMap.put(new Integer(654), "Siena Black (italic)");
    _fontnameMap.put(new Integer(655), "Yearbook");
    _fontnameMap.put(new Integer(656), "Koloss (extra bold)");
    _fontnameMap.put(new Integer(657), "Phenix American (extra condensed)");
    _fontnameMap.put(new Integer(658), "PL Bernhardt");
    _fontnameMap.put(new Integer(659), "Orlando Caps");
    _fontnameMap.put(new Integer(659), "PL Barclay Outline (outline)");
    _fontnameMap.put(new Integer(660), "PL Britannia Bold");
    _fontnameMap.put(new Integer(661), "PL Fiorello Condensed");
    _fontnameMap.put(new Integer(662), "Fluidum Bold (italic)");
    _fontnameMap.put(new Integer(663), "Woodblock (bold)");
    _fontnameMap.put(new Integer(663), "Sinaloa (pattern 0)");
    _fontnameMap.put(new Integer(664), "Stratford Extra Bold");
    _fontnameMap.put(new Integer(664), "Matra (pattern 0)");
    _fontnameMap.put(new Integer(665), "PL Tower Condensed");
    _fontnameMap.put(new Integer(666), "Section Bold Condensed");
    _fontnameMap.put(new Integer(667), "Miehle Condensed");
    _fontnameMap.put(new Integer(668), "Phyllis");
    _fontnameMap.put(new Integer(669), "Modernique (extra bold)");
    _fontnameMap.put(new Integer(670), "Egyptienne F");
    _fontnameMap.put(new Integer(671), "Post Antiqua (B.metrics)");
    _fontnameMap.put(new Integer(672), "Diotima");
    _fontnameMap.put(new Integer(673), "Aldus");
    _fontnameMap.put(new Integer(674), "Chaplin (italic)");
    _fontnameMap.put(new Integer(675), "Uncle Sam Stars (pattern 0, shadow)");
    _fontnameMap.put(new Integer(675), "Uncle Sam Stripes (pattern 1, shadow)");
    _fontnameMap.put(new Integer(676), "Wildstyle");
    _fontnameMap.put(new Integer(677), "Logan (pattern 0)");
    // _fontnameMap.put(new Integer(677), "Eon Age (pattern 1)");
    // _fontnameMap.put(new Integer(677), "System X3 (pattern 2)");
    // _fontnameMap.put(new Integer(677), "Galaxy Run (pattern 3)");
    _fontnameMap.put(new Integer(678), "Jukebox (bold condensed)");
    _fontnameMap.put(new Integer(679), "Marking Numbers Squares");
    // _fontnameMap.put(new Integer(679), "Al Harf Al Jadid");
    _fontnameMap.put(new Integer(680), "Vivaldi");
    _fontnameMap.put(new Integer(681), "Codex");
    _fontnameMap.put(new Integer(682),
            "Metronome Gothic (bold extra condensed)");
    _fontnameMap.put(new Integer(683), "Salut (bold)");
    _fontnameMap.put(new Integer(684), "Lucida Fax");
    _fontnameMap.put(new Integer(685), "Bellevue");
    _fontnameMap.put(new Integer(686), "Architect");
    _fontnameMap.put(new Integer(687), "Beton Extra Bold");
    _fontnameMap.put(new Integer(688),
            "Metropolis (extra bold, solid & inline)");
    _fontnameMap.put(new Integer(689), "PL Davison Zip Bold");
    _fontnameMap.put(new Integer(690), "Neon (Nebiolo)");
    _fontnameMap.put(new Integer(691), "PL Benguiat Frisky");
    _fontnameMap.put(new Integer(692), "PL Bartuska Trophy Oblique");
    _fontnameMap.put(new Integer(693), "Cable");
    _fontnameMap.put(new Integer(694), "PL Brazilia");
    _fontnameMap.put(new Integer(695), "PL Radiant");
    _fontnameMap.put(new Integer(696), "Ritmo Bold (italic)");
    _fontnameMap.put(new Integer(697), "PL Fiedler Gothic Bold");
    _fontnameMap.put(new Integer(698), "Egiziano Black");
    _fontnameMap.put(new Integer(699), "Studio");
    _fontnameMap.put(new Integer(700), "PL Futura Maxi");
    _fontnameMap.put(new Integer(701), "Solemnis");
    _fontnameMap.put(new Integer(702), "Quirinus Bold (condensed)");
    _fontnameMap.put(new Integer(703),
            "PL West Behemoth Semi Condensed (XBd Cd)");
    _fontnameMap.put(new Integer(704), "Renault");
    _fontnameMap.put(new Integer(705), "Forbes Bold");
    _fontnameMap.put(new Integer(706), "Mobil");
    _fontnameMap.put(new Integer(707), "Becket");
    _fontnameMap.put(new Integer(708), "Lucida Sans Typewriter");
    _fontnameMap.put(new Integer(709), "Cartoon Script Roman");
    _fontnameMap.put(new Integer(710), "Campanula");
    _fontnameMap.put(new Integer(711), "Odilia");
    _fontnameMap.put(new Integer(712), "Lino Letter");
    _fontnameMap.put(new Integer(713), "Henche");
    _fontnameMap.put(new Integer(714), "Mahlau (condensed)");
    _fontnameMap.put(new Integer(715), "Aquarias No. 8 (bold)");
    _fontnameMap.put(new Integer(716), "CG Frontiera");
    _fontnameMap.put(new Integer(717), "Globe Gothic");
    _fontnameMap.put(new Integer(718), "Signature");
    _fontnameMap.put(new Integer(719), "Sans Serif Stencil");
    _fontnameMap.put(new Integer(720), "Boldface PS");
    _fontnameMap.put(new Integer(721), "Title PS");
    _fontnameMap.put(new Integer(725), "Hess Neobold");
    _fontnameMap.put(new Integer(726), "Hollandse Mediaeval");
    _fontnameMap.put(new Integer(727), "Holland Seminar");
    _fontnameMap.put(new Integer(728), "CG Cloister");
    _fontnameMap.put(new Integer(729), "Adroit");
    _fontnameMap.put(new Integer(730), "Claire News");
    _fontnameMap.put(new Integer(731), "Triplett");
    _fontnameMap.put(new Integer(732), "Accolade");
    _fontnameMap.put(new Integer(733), "Claridge");
    _fontnameMap.put(new Integer(734), "Alpin Gothic");
    _fontnameMap.put(new Integer(735), "Geometric");
    _fontnameMap.put(new Integer(736), "Heldustry");
    _fontnameMap.put(new Integer(737), "Busorama");
    _fontnameMap.put(new Integer(738), "Salto");
    _fontnameMap.put(new Integer(739), "Fehrle Display");
    _fontnameMap.put(new Integer(740), "Kismet");
    _fontnameMap.put(new Integer(741), "Digi Fraktur");
    _fontnameMap.put(new Integer(742), "Anglia");
    _fontnameMap.put(new Integer(743), "Jiffy");
    _fontnameMap.put(new Integer(744), "Rosewood");
    _fontnameMap.put(new Integer(745), "Zebrawood");
    _fontnameMap.put(new Integer(746), "Pepperwood (condensed)");
    _fontnameMap.put(new Integer(747), "Copal (solid)");
    _fontnameMap.put(new Integer(747), "Copal (outline, patterned)");
    _fontnameMap.put(new Integer(748), "Motter Corpus (extrabold)");
    _fontnameMap.put(new Integer(749), "Cerigo");
    _fontnameMap.put(new Integer(750), "Caflisch Script");
    _fontnameMap.put(new Integer(751), "Mezz");
    _fontnameMap.put(new Integer(752), "Nueva");
    _fontnameMap.put(new Integer(753), "Penumbra");
    _fontnameMap.put(new Integer(754), "Sanvito");
    _fontnameMap.put(new Integer(755), "Viva");
    _fontnameMap.put(new Integer(756), "Alexa (italic)");
    // _fontnameMap.put(new Integer(756), "Balzano");
    // _fontnameMap.put(new Integer(756), "Caliban (condensed italic)");
    _fontnameMap.put(new Integer(757), "Ex Ponto");
    _fontnameMap.put(new Integer(758), "Neue Hammer Unziale 1");
    _fontnameMap.put(new Integer(758), "Neue Hammer Unziale 2 (edge)");
    _fontnameMap.put(new Integer(759), "Galahad");
    _fontnameMap.put(new Integer(760), "LiShu (China)");
    // _fontnameMap.put(new Integer(760), "Gungse (Korean)");
    // _fontnameMap.put(new Integer(760),
    // "HanYang GungSe Proportional (Korean)");
    _fontnameMap.put(new Integer(761), "Yuang (Yuan, XiYuang - China)");
    _fontnameMap.put(new Integer(762), "Miryam");
    _fontnameMap.put(new Integer(763), "Ryadh");
    _fontnameMap.put(new Integer(764), "Arkona (ital script)");
    _fontnameMap.put(new Integer(765), "El Greco (ital script)");
    _fontnameMap.put(new Integer(766), "Aja (ital script)");
    _fontnameMap.put(new Integer(767), "Poppl-Exquisit (ital script)");
    _fontnameMap.put(new Integer(768), "Sassafras Roman");
    _fontnameMap.put(new Integer(769), "Kigali Roman");
    _fontnameMap.put(new Integer(770), "Rundfunk Antiqua");
    _fontnameMap.put(new Integer(771), "Rundfunk Grotesk");
    _fontnameMap.put(new Integer(772), "Apolline");
    _fontnameMap.put(new Integer(773), "Alisal");
    _fontnameMap.put(new Integer(774), "Strider");
    _fontnameMap.put(new Integer(775), "Throhand");
    _fontnameMap.put(new Integer(776), "Cicero (e should be e-acute)");
    _fontnameMap.put(new Integer(777), "Antique Condensed Two");
    _fontnameMap.put(new Integer(778), "Asphalt Black");
    _fontnameMap.put(new Integer(779), "Avalon");
    _fontnameMap.put(new Integer(780), "Brok");
    _fontnameMap.put(new Integer(781), "Citadel");
    _fontnameMap.put(new Integer(782), "Hermes");
    _fontnameMap.put(new Integer(783), "Lafayette");
    _fontnameMap.put(new Integer(784), "Narcissus");
    _fontnameMap.put(new Integer(785), "Pilsner");
    _fontnameMap.put(new Integer(786), "Showcard Moderne");
    _fontnameMap.put(new Integer(787), "Streamline");
    _fontnameMap.put(new Integer(788), "Scherzo");
    _fontnameMap.put(new Integer(789), "Jante Antiqua");
    _fontnameMap.put(new Integer(790), "Albers Architype");
    _fontnameMap.put(new Integer(791), "Aubette Architype");
    _fontnameMap.put(new Integer(792), "Ballmer Architype");
    _fontnameMap.put(new Integer(793), "Bayer Type Architype");
    _fontnameMap.put(new Integer(794), "Schwitters Architype");
    _fontnameMap.put(new Integer(795), "Crane");
    _fontnameMap.put(new Integer(796), "Runa Serif");
    _fontnameMap.put(new Integer(797), "Comedia Serif");
    _fontnameMap.put(new Integer(798), "Breadline Normal");
    _fontnameMap.put(new Integer(799), "Revolution Normal");
    _fontnameMap.put(new Integer(800), "Virgin Roman Normal");
    _fontnameMap.put(new Integer(801), "Gararond");
    _fontnameMap.put(new Integer(802), "Abacus");
    _fontnameMap.put(new Integer(803), "Classic");
    _fontnameMap.put(new Integer(804), "Cupid");
    _fontnameMap.put(new Integer(805), "Arepo");
    _fontnameMap.put(new Integer(806), "Aureus Uncial (upright)");
    _fontnameMap.put(new Integer(807), "Connach (upright, norm and uncial lc)");
    _fontnameMap.put(new Integer(808), "Cresci Rotunda (upright)");
    _fontnameMap.put(new Integer(809), "Donatello (italic, black italic)");
    _fontnameMap.put(new Integer(810), "Francesca (lombardic, upright & cond)");
    _fontnameMap.put(new Integer(810), "Lombardic Capitals (upright)");
    _fontnameMap.put(new Integer(811), "Ludovico Smooth (italic & flourishes)");
    _fontnameMap
            .put(new Integer(811), "Ludovico Woodcut (italic & flourishes)");
    _fontnameMap.put(new Integer(812), "Mantegna (italic)");
    _fontnameMap.put(new Integer(813), "Palatino Rotunda (upright)");
    _fontnameMap.put(new Integer(814), "Percival (upright)");
    _fontnameMap.put(new Integer(815), "Wolfdance (italic)");
    _fontnameMap.put(new Integer(816), "Adastra (bold italic inline)");
    _fontnameMap.put(new Integer(817), "Ampersands");
    _fontnameMap.put(new Integer(818), "Arwen (upright)");
    _fontnameMap.put(new Integer(819), "Blocks (upright, solid filled)");
    _fontnameMap.put(new Integer(820), "Elegant (inline & outline)");
    _fontnameMap.put(new Integer(821), "Poetry (solid & inline)");
    _fontnameMap.put(new Integer(822), "Sphinx (extrabold, solid & inline)");
    _fontnameMap.put(new Integer(823), "Tube (upright)");
    _fontnameMap
            .put(new Integer(824), "Searsucker (solid, outline, patterned)");
    _fontnameMap.put(new Integer(825), "Hindenburg (upright)");
    _fontnameMap.put(new Integer(826), "Informal (black, norm & condensed)");
    _fontnameMap.put(new Integer(827), "Marquis (upright)");
    _fontnameMap.put(new Integer(828), "Questions");
    _fontnameMap.put(new Integer(829), "Maximilian (upright, inline)");
    _fontnameMap.put(new Integer(830), "Minimal (upright thin)");
    _fontnameMap.put(new Integer(831), "Stalk (upright inline)");
    _fontnameMap.put(new Integer(832), "Mariposa (family)");
    _fontnameMap.put(new Integer(833), "Mariposa Sans (family)");
    _fontnameMap.put(new Integer(834), "Corvallis (upright & italic)");
    _fontnameMap.put(new Integer(835), "Corvallis Sans (upright & italic)");
    _fontnameMap.put(new Integer(836), "Alligators");
    _fontnameMap.put(new Integer(837), "Carmela (italic)");
    _fontnameMap.put(new Integer(838), "Dorothea (upright)");
    _fontnameMap.put(new Integer(839), "Hrabanus (upright)");
    _fontnameMap.put(new Integer(840), "Lexie�s Animals");
    _fontnameMap.put(new Integer(841), "Mexican Birds");
    _fontnameMap.put(new Integer(841), "Mexican Borders");
    _fontnameMap.put(new Integer(841), "Mexican Symbols");
    _fontnameMap.put(new Integer(842), "Monmouth (upright)");
    _fontnameMap.put(new Integer(843), "Neuhengen (upright)");
    _fontnameMap.put(new Integer(844), "Ophelia Italic");
    _fontnameMap.put(new Integer(845), "Poggio Bookhand (upright)");
    _fontnameMap.put(new Integer(846), "Pompeii Capitals (upright)");
    _fontnameMap.put(new Integer(847), "Ramsey (upright)");
    _fontnameMap.put(new Integer(848), "Sallando Italic");
    _fontnameMap.put(new Integer(849), "Thalia Italic");
    _fontnameMap.put(new Integer(850), "Trieste (upright)");
    _fontnameMap.put(new Integer(851), "Connach Historic");
    _fontnameMap.put(new Integer(852), "Lombardic Caps");
    _fontnameMap.put(new Integer(853), "Ludovico Smooth Flourish");
    _fontnameMap.put(new Integer(853), "Ludovico Woodcut Flourish");
    _fontnameMap.put(new Integer(854), "Newton Inline");
    _fontnameMap.put(new Integer(855), "Lucida Typewriter");
    _fontnameMap.put(new Integer(930), "Akzidenz Grotesk Buch Rounded");
    _fontnameMap.put(new Integer(1030), "Isil Gothic");
    _fontnameMap.put(new Integer(2128), "HanYang Batang Fixed Pitch (Korean)");
    _fontnameMap.put(new Integer(2128), "MS Mincho (Japan, Proportional)");
    _fontnameMap.put(new Integer(2200), "HanYang Gulrim Fixed Pitch (Korean)");
    _fontnameMap.put(new Integer(2201), "HanYang Dotum Fixed Pitch (Korean)");
    _fontnameMap.put(new Integer(2201), "MS Gothic (Japan, Proportional)");
    _fontnameMap.put(new Integer(2549), "Ming Light (Japan, Proportional)");
    _fontnameMap.put(new Integer(2730), "Wingdings");
    _fontnameMap.put(new Integer(2808), "HanYang GungSe Fixed Pitch (Korean)");
    _fontnameMap.put(new Integer(2800), "Serif"); // standard java font
    _fontnameMap.put(new Integer(2801), "SansSerif"); // standard java font
  }
}
